---

- name: install
  apt:
    name: glusterfs-server
    state: present
  tags:
    - gluster_server_install
    - gluster_server
    - install

- name: probe peers
  command: gluster peer probe "{{ item }}"
  with_items: gluster_server_hostnames
  tags:
    - gluster_server_install
    - gluster_server
    - install

- name: create brick mount points
  file:
    path: "{{ gluster_server_brick_path }}/{{ gluster_server_volume_name }}"
    state: directory
  tags:
    - gluster_server_configure
    - gluster_server
    - configure
    - create_mountpoints

- name: create volume
  command: gluster volume create {{ gluster_server_volume_name }} {{ _gluster_server_volume_create_args[gluster_server_volume_type] }} {{ gluster_server_hostnames | join(':'+gluster_server_brick_path + '/' + gluster_server_volume_name + ' ') }}:{{ gluster_server_brick_path }}/{{ gluster_server_volume_name }} {{ 'force' if gluster_server_volume_create_force else '' }}
  register: volume_create
  failed_when: volume_create.rc != 0 and not ('Please try again after sometime.' in volume_create.stderr or 'already exists' in volume_create.stderr)
  changed_when: volume_create.rc == 0
  tags:
    - gluster_server_configure
    - gluster_server
    - configure
    - volume_create

- name: start volume
  command: gluster volume start {{ gluster_server_volume_name }}
  register: volume_start
  failed_when: volume_start.rc != 0 and not ('Please try again after sometime' in volume_start.stderr or 'already started' in volume_start.stderr)
  changed_when: volume_start.rc == 0
  tags:
    - gluster_server_configure
    - gluster_server
    - configure
    - volume_start