#!/usr/bin/env bash

usage() {
    cat <<EOF
Usage: $0 <name>

Description: Setup a new virtualcluster environment.

Examples:

  $ $0 mesos
  $ $0 hadoop
EOF
}

name="$1"

case "$name" in
    ""|"-h"|"--help")
        usage
        exit 1
        ;;
    *)
        ;;
esac

if test -d "$name"; then
    echo "$name already exists!"
    exit 2
fi

mkdir -p "$name"

set -x
cd "$name"
cp ../templates/ansible.cfg .
cp ../templates/deploy-extra.sh .
cp ../templates/machines.yml .
cp ../templates/site.yml .
cp ../templates/requirements.txt .
ln -s ../deploy.sh .
ln -s ../scripts .
ln -s ../Vagrantfile .
