---

- hosts: all
  sudo: yes
  tasks:
    - name: update cache
      apt:
        update_cache: yes

    - name: install common packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - emacs24-nox
        - curl
        - wget
        - httpie

    - name: set hosts
      copy:
        src: hosts
        dest: /etc/hosts

- hosts: all
  sudo: yes
  vars:
    mesos_version: 0.23.0
    mesos_checksums:
      0.23.0: b967355ec1f7cf9ffcef76b58939ed48dd4975ea90d1c976669b50c589bdbdec

  tasks:

    - name: add mesos key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: E56151BF
        state: present

    - name: add mesosphere repository
      apt_repository:
        repo: >-
          deb http://repos.mesosphere.com/ubuntu trusty main

    - name: update cache
      apt:
        update_cache: yes

- hosts: zookeeper
  sudo: yes
  vars:
    zookeeper_nodes: "{{ groups['zookeeper'] }}"
    zookeeper_node_iface: ansible_eth1

  tasks:


    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - zookeeper
        - zookeeper-bin
        - zookeeperd

    - name: set instance id
      template:
        src: myid.j2
        dest: /etc/zookeeper/conf/myid
      tags: zk_conf

    - name: configure
      template:
        src: zoo.cfg.j2
        dest: /etc/zookeeper/conf/zoo.cfg
      tags: zk_conf

    - name: restart zookeeper
      service:
        name: zookeeper
        state: restarted
      tags: zk_conf

- hosts: mesos_master:mesos_slave
  sudo: yes
  tasks:
  
    - name: create dir
      file:
        path: /etc/mesos
        state: directory
      tags: zk_conf

    - name: set zookeeper location
      copy:
        dest: /etc/mesos/zk
        src: zk_url.txt
      tags: zk_conf


- hosts: mesos_master
  sudo: yes
  vars:
    mesos_zk_node_iface: ansible_eth1
    mesos_zk_port: 2181
    mesos_quorum: >-
      {{ ((groups.mesos_master | length) / 2) | round(method='ceil') | int }}

  tasks:

    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mesos
        - marathon
        - zookeeper

    - name: set quorum
      copy:
        content: "{{ mesos_quorum }}"
        dest: /etc/mesos-master/quorum
      tags: mesos_conf

    - name: set hostname
      copy:
        content: "{{ ansible_eth1.ipv4.address }}"
        dest: /etc/mesos-master/hostname
      tags: mesos_conf

    - name: start services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - mesos-master
        - marathon
      tags: mesos_service

- hosts: mesos_slave
  sudo: yes
  tasks:

    - name: disable zookeeper
      copy:
        content: manual
        dest: "/etc/init/{{ item }}.override"
      with_items:
        - zookeeper
        - mesos-master

    - name: install packages
      apt:
        name: mesos
        state: present

    - name: set hostname
      copy:
        content: "{{ ansible_eth1.ipv4.address }}"
        dest: /etc/mesos-slave/hostname
      tags: mesos_conf


    - name: start services
      service:
        name: mesos-slave
        state: restarted
      tags: mesos_service