---

- name: set hadoop_home
  set_fact:
    hadoop_home: "{{ ansible_env.PWD }}/{{ hadoop_home_name }}"
  tags: hadoop_install
  

- name: fetch hadoop
  get_url:
    url: "{{ hadoop_url }}"
    dest: "{{ ansible_env.PWD }}/{{ hadoop_archive_name }}"
    sha256sum: "{{ hadoop_archive_sha256 }}"
  tags: hadoop_install

- name: extract hadoop
  command: tar xvf {{ hadoop_archive_name }} creates={{ hadoop_extracted_name }}
  tags: hadoop_install

- name: create symlink shortcut
  file:
    src: "{{ ansible_env.PWD }}/{{ hadoop_extracted_name }}"
    dest: "{{ hadoop_home }}"
    state: link
  tags: hadoop_install

- name: set environment exports
  lineinfile:
    dest: ".bashrc"
    line: "export {{ item }}"
    insertbefore: BOF
  with_items:
    - HADOOP_PID_DIR=$HADOOP_HOME/pid
    - PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
    - HADOOP_HOME={{ hadoop_home }}
    - JAVA_HOME=$(dirname $(dirname $(dirname $(update-alternatives --list java))))
  tags: hadoop_install
