---

- name: common
  hosts: all
  sudo: yes
  tasks:
    - name: common | update cache
      apt:
        update_cache: yes
      tags: common

    - name: common | install common packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - emacs24-nox
        - curl
        - wget
        - httpie
      tags: common

    - name: common | set hosts
      copy:
        src: hosts
        dest: /etc/hosts
      tags: common

- name: mesos repo
  hosts: all
  sudo: yes
  tasks:

    - name: mesos repo | add mesos key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: E56151BF
        state: present
      tags: mesos_repo

    - name: mesos repo | add mesosphere repository
      apt_repository:
        repo: >-
          deb http://repos.mesosphere.com/ubuntu trusty main
      tags: mesos_repo

    - name: mesos repo | update cache
      apt:
        update_cache: yes
      tags: mesos_repo

- name: zookeeper
  hosts: zookeeper
  sudo: yes
  vars:
    zookeeper_nodes: "{{ groups['zookeeper'] }}"
    zookeeper_node_iface: ansible_eth1

  tasks:

    - name: zookeeper | install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - zookeeper
        - zookeeper-bin
        - zookeeperd
      tags: zk_install

    - name: zookeeper | set instance id
      template:
        src: myid.j2
        dest: /etc/zookeeper/conf/myid
      tags: zk_conf

    - name: zookeeper | configure
      template:
        src: zoo.cfg.j2
        dest: /etc/zookeeper/conf/zoo.cfg
      tags: zk_conf

    - name: zookeeper | restart zookeeper
      service:
        name: zookeeper
        state: restarted
      tags: zk_conf


- name: zookeeper
  hosts: all:!zookeeper
  sudo: yes
  tasks:

    - name: zookeeper | disable zookeeper
      copy:
        content: manual
        dest: "/etc/init/{{ item }}.override"
      with_items:
        - zookeeper
        - mesos-master
      tags: zk_conf


- name: zookeeper
  hosts: mesos_master:mesos_slave
  sudo: yes
  tasks:

    - name: zookeeper | create dir
      file:
        path: /etc/mesos
        state: directory
      tags: zk_conf

    - name: zookeeper | set zookeeper location
      copy:
        dest: /etc/mesos/zk
        src: zk_url.txt
      tags: zk_conf


- name: mesos master
  hosts: mesos_master
  sudo: yes
  vars:
    mesos_zk_node_iface: ansible_eth1
    mesos_zk_port: 2181
    mesos_quorum: >-
      {{ ((groups.mesos_master | length) / 2) | round(method='ceil') | int }}

  tasks:

    - name: mesos master | install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mesos
      tags: mesos_install

    - name: mesos master | set quorum
      copy:
        content: "{{ mesos_quorum }}"
        dest: /etc/mesos-master/quorum
      tags: mesos_conf

    - name: mesos master | set mesos hostname
      copy:
        content: "{{ ansible_eth1.ipv4.address }}"
        dest: /etc/mesos-master/hostname
      tags: mesos_conf

    - name: mesos master | start services
      service:
        name: mesos-master
        state: restarted
      tags: mesos_service

- name: marathon
  hosts: marathon
  sudo: yes
  tasks:

    - name: marathon | install marathon
      apt:
        name: marathon
        state: present
      tags: marathon_install

    - name: marathon | make marathon conf dir
      file:
        path: /etc/marathon/conf
        state: directory
      tags: marathon_conf

    - name: marathon | set marathon hostname
      copy:
        content: "{{ ansible_eth1.ipv4.address }}"
        dest: /etc/marathon/conf/hostname
      tags: marathon_conf

    - name: marathon | start services
      service:
        name: marathon
        state: restarted
      tags: marathon_service


- name: chronos
  hosts: chronos
  sudo: yes
  vars:

    chronos_http_port: 8081
    chronos_zk_path: /chronos
    chronos_zk_port: 2181
    chronos_zk_hosts: >-
      {{ hostvars[groups.mesos_master[0]].ansible_eth1.ipv4.address }}:{{ chronos_zk_port }}

  tasks:

    - name: chronos | install chronos
      apt:
        name: chronos
        state: present
      tags: chronos_install

    - name: chronos | set chronos hostname
      copy:
        content: "{{ ansible_eth1.ipv4.address }}"
        dest: /etc/chronos/conf/hostname
      tags: chronos_conf

    - name: chronos | set chronos http_port
      copy:
        content: "{{ chronos_http_port }}"
        dest: /etc/chronos/conf/http_port
      tags: chronos_conf

    - name: chronos | start chronos
      service:
        name: chronos
        state: restarted
      tags: chronos_service

- name: mesos slave
  hosts: mesos_slave
  sudo: yes
  tasks:

    - name: mesos slave | install packages
      apt:
        name: mesos
        state: present

    - name: mesos slave | set hostname
      copy:
        content: "{{ ansible_eth1.ipv4.address }}"
        dest: /etc/mesos-slave/hostname
      tags: mesos_conf


    - name: mesos slave | start services
      service:
        name: mesos-slave
        state: restarted
      tags: mesos_service
