---

- hosts: all
  sudo: yes
  tasks:
    - name: update cache
      apt:
        update_cache: yes
      tags: common

    - name: install common packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - emacs24-nox
        - curl
        - wget
        - httpie
      tags: common

    - name: set hosts
      copy:
        src: hosts
        dest: /etc/hosts
      tags: common

- hosts: all
  sudo: yes
  tasks:

    - name: add mesos key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: E56151BF
        state: present
      tags: mesos_repo

    - name: add mesosphere repository
      apt_repository:
        repo: >-
          deb http://repos.mesosphere.com/ubuntu trusty main
      tags: mesos_repo

    - name: update cache
      apt:
        update_cache: yes
      tags: mesos_repo

- hosts: zookeeper
  sudo: yes
  vars:
    zookeeper_nodes: "{{ groups['zookeeper'] }}"
    zookeeper_node_iface: ansible_eth1

  tasks:

    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - zookeeper
        - zookeeper-bin
        - zookeeperd
      tags: zk_install

    - name: set instance id
      template:
        src: myid.j2
        dest: /etc/zookeeper/conf/myid
      tags: zk_conf

    - name: configure
      template:
        src: zoo.cfg.j2
        dest: /etc/zookeeper/conf/zoo.cfg
      tags: zk_conf

    - name: restart zookeeper
      service:
        name: zookeeper
        state: restarted
      tags: zk_conf


- hosts: all:!zookeeper
  sudo: yes
  tasks:

    - name: disable zookeeper
      copy:
        content: manual
        dest: "/etc/init/{{ item }}.override"
      with_items:
        - zookeeper
        - mesos-master
      tags: zk_conf


- hosts: mesos_master:mesos_slave
  sudo: yes
  tasks:

    - name: create dir
      file:
        path: /etc/mesos
        state: directory
      tags: zk_conf

    - name: set zookeeper location
      copy:
        dest: /etc/mesos/zk
        src: zk_url.txt
      tags: zk_conf


- hosts: mesos_master
  sudo: yes
  vars:
    mesos_zk_node_iface: ansible_eth1
    mesos_zk_port: 2181
    mesos_quorum: >-
      {{ ((groups.mesos_master | length) / 2) | round(method='ceil') | int }}

  tasks:

    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mesos
      tags: mesos_install

    - name: set quorum
      copy:
        content: "{{ mesos_quorum }}"
        dest: /etc/mesos-master/quorum
      tags: mesos_conf

    - name: set mesos hostname
      copy:
        content: "{{ ansible_eth1.ipv4.address }}"
        dest: /etc/mesos-master/hostname
      tags: mesos_conf

    - name: start services
      service:
        name: mesos-master
        state: restarted
      tags: mesos_service

- hosts: marathon
  sudo: yes
  tasks:

    - name: install marathon
      apt:
        name: marathon
        state: present
      tags: marathon_install

    - name: make marathon conf dir
      file:
        path: /etc/marathon/conf
        state: directory
      tags: marathon_conf

    - name: set marathon hostname
      copy:
        content: "{{ ansible_eth1.ipv4.address }}"
        dest: /etc/marathon/conf/hostname
      tags: marathon_conf

    - name: start services
      service:
        name: marathon
        state: restarted
      tags: marathon_service


- hosts: mesos_slave
  sudo: yes
  tasks:

    - name: install packages
      apt:
        name: mesos
        state: present

    - name: set hostname
      copy:
        content: "{{ ansible_eth1.ipv4.address }}"
        dest: /etc/mesos-slave/hostname
      tags: mesos_conf


    - name: start services
      service:
        name: mesos-slave
        state: restarted
      tags: mesos_service
