---

- name: common
  hosts: all
  sudo: yes
  roles:

    - role: common

      package_list:
        - emacs24-nox
        - curl
        - httpie
        - ssh
        - rsync
        - parted
        - iotop
        - facter

      services_running:
        - ssh

      groups_managed:
        hadoopadmin:
        hadoopuser:
