---

- name: ganglia monitor
  hosts: monitor[0]
  sudo: yes
  roles:
    - role: ganglia_metad
    - role: ganglia_web

- name: ganglia nodes
  hosts: all
  sudo: yes
  roles:
    - role: ganglia_mond
      ganglia_udp_send_channels:
        - host: "{{ hostvars[groups['monitor'][0]].ansible_eth0.ipv4.address }}"
          port: "{{ ganglia_defaults_gmon_port }}"
