---

- name: gluster
  hosts: glusternodes
  sudo: yes
  roles:
    - role: gluster_server
      gluster_server_hostnames: "{{ groups['glusternodes'] }}"
      gluster_server_volume_type: stripe
      gluster_server_volume_stripe_count: "{{ groups['glusternodes'] | length}}"
      gluster_server_volume_name: gluster
      gluster_server_volume_create_force: yes


- name: gluster clients
  hosts: glusternodes
  sudo: yes
  vars:
    usernames: "{{ lookup('pipe', 'cat users.txt').split('\n') }}"
  tasks:
    - name: install client
      apt: name=glusterfs-client state=present
      tags:
        - gluster_client_install
        - gluster_client
        - install

    - name: create the root directory
      file:
        path: /gluster
        state: directory
      tags:
        - gluster_client_configure
        - gluster_client
        - configure

    - name: mount
      command: mount -t glusterfs -o acl "{{ groups['glusternodes'][0] }}:/gluster" "/gluster"
      tags:
        - gluster_client_mount
        - gluster_client
        - mount

    - name: create user directories
      command: mkdir -p /gluster/{{ item }}
      command: chown -R {{ item }}:{{ item }} /gluster/{{ item }}
      with_items: usernames
      tags:
        - gluster_client_configure
        - gluster_client
        - configure


    - name: create shared directory
      file:
        src: "/gluster/{{ item }}"
        dest: "/home/{{ item }}/share"
        state: link
        owner: "{{ item }}"
        group: "{{ item }}"
      with_items: usernames
      tags:
        - gluster_client_configure
        - gluster_client
        - configure
