---

############################################################ server

- name: gluster
  hosts: glusternodes
  sudo: yes
  tasks:

    - name: install
      apt:
        name: glusterfs-server
        state: present
      tags:
        - gluster_server_install
        - gluster_server
        - install

    - name: create brick mount points
      file:
        path: /export/glusterfs/gluster
        state: directory
      tags:
        - gluster_server_configure
        - gluster_server
        - configure
        - create_mountpoints

############################################################ peers

- name: gluster
  hosts: glusternodes[0]
  sudo: yes
  tasks:
    - name: probe peers
      command: gluster peer probe "{{ item }}"
      with_items:
        - "{{ groups['glusternodes'][1] }}"
      tags:
        - gluster_server_probe
        - gluster_server
        - probe


- name: gluster
  hosts: glusternodes[1]
  sudo: yes
  tasks:

    - name: probe peers
      command: gluster peer probe "{{ item }}"
      with_items: "{{ groups['glusternodes'] }}"
      tags:
        - gluster_server_probe
        - gluster_server
        - probe


############################################################ volumes

- name: gluster
  hosts: glusternodes[0]
  sudo: yes
  tasks:

    - name: create volume
      command: gluster volume create gluster strip {{ groups['glusternodes'] | length }} {{ groups['glusternodes'] | join(':/export/glusterfs/gluster' + ' ') }}:/export/glusterfs/gluster force
      tags:
        - gluster_server_volume_create
        - gluster_server
        - volume_create

    - name: start volume
      command: gluster volume start gluster
      tags:
        - gluster_server_volume_start
        - gluster_server
        - volume_start

############################################################ clients

- name: gluster clients
  hosts: frontends
  sudo: yes
  vars:
    usernames: "{{ lookup('pipe', 'cat users.txt').split('\n') }}"
  tasks:
    - name: install client
      apt: name=glusterfs-client state=present
      tags:
        - gluster_client_install
        - gluster_client
        - install

    - name: create the root directory
      file:
        path: /gluster
        state: directory
      tags:
        - gluster_client_configure
        - gluster_client
        - configure

    - name: mount
      mount:
        fstype: glusterfs
        src: "{{ groups['glusternodes'][0] }}:/gluster"
        name: "/gluster"
        state: mounted
      tags:
        - gluster_client_mount
        - gluster_client
        - mount

    - name: create shared directory
      file:
        src: "/gluster/{{ item }}"
        dest: "/home/{{ item }}/share"
        state: link
        force: yes
        owner: "{{ item }}"
        group: "{{ item }}"
      with_items: usernames
      tags:
        - gluster_client_configure
        - gluster_client
        - configure


- name: gluster clients
  hosts: frontends[0]
  sudo: yes
  vars:
    usernames: "{{ lookup('pipe', 'cat users.txt').split('\n') }}"
  tasks:

    - name: create user directories
      file:
        path: "/gluster/{{ item }}"
        state: directory
        owner: "{{ item }}"
        group: "{{ item }}"
      with_items: usernames
      tags:
        - gluster_client_configure
        - gluster_client
        - configure
