#!/usr/bin/env python

import lib

if __name__ == '__main__':
    import sys
    spec_path = sys.argv[1]
    spec = lib.read_spec(spec_path)
    machines = spec['machines']
    for m in machines:
        print m['name']
