#!/usr/bin/env python

import lib

localhost_entry_ipv4 = '127.0.0.1 localhost'
localhost_entry_ipv6 = '::1 localhost'
    

def hosts_file_entry(spec, node, attr='ip'):
    domain = lib.get_with_defaults(node, 'domain_name', spec)
    hostname = node['name']

    fqdn = '{hn}.{dn}'.format(
        hn=hostname,
        dn=domain)

    entry = '{ip} {hn} {fqdn}'.format(
        ip=node[attr],
        hn=hostname,
        fqdn=fqdn)

    return entry


def hosts_file(spec, attr='ip'):

    entries = [
        localhost_entry_ipv4,
        localhost_entry_ipv6
    ] + [
        hosts_file_entry(spec, node, attr=attr)
        for node in spec['machines']
    ]

    return '\n'.join(entries)

if __name__ == '__main__':
    import sys
    spec_path = sys.argv[1]
    try:
        attr = sys.argv[2]
    except IndexError:
        attr = 'ip'

    spec = lib.read_spec(spec_path)
    hosts = hosts_file(spec, attr=attr)
    print hosts
