#!/usr/bin/env python

import lib
import yaml


def mk_inventory_entry(**kws):
    return """\
{name} \
ansible_ssh_host={ip} \
ansible_ssh_private_key_file={key}\
""".format(**kws)

def dump_inventory(spec):
    name_to_node = lib.build_inventory_mapping(spec)

    for groupname, group in lib.inventory(spec):

        print '[{}]'.format(groupname)

        for node in group:
            key = lib.get_with_defaults(node, 'key_path', spec)
            key_path = lib.fullpath(key)

            entry = mk_inventory_entry(
                name=node['name'],
                ip=node['ip'],
                key=key_path)
            print entry

        print


if __name__ == '__main__':
    import sys
    spec_path = sys.argv[1]
    spec = lib.read_spec(spec_path)
    dump_inventory(spec)
