#!/usr/bin/env python

import lib
import yaml
import os
import os.path

def dump(vars):
    return yaml.dump(vars, default_flow_style=False, default_style='')


def write_vars(spec, key, outdir):

    if key not in spec: return

    if not os.path.exists(outdir):
        os.makedirs(outdir)


    for hostgroup, vars in spec[key].iteritems():

        out = os.path.join(outdir, hostgroup)

        if os.path.exists(out):
            y = lib.read_spec(out)
            vars.update(y)
            
        with open(out, 'w') as fd:
            fd.write(dump(vars))




if __name__ == '__main__':
    import sys
    spec_path = sys.argv[1]
    spec = lib.read_spec(spec_path)

    write_vars(spec, 'hostvars', 'host_vars')
    write_vars(spec, 'groupvars', 'group_vars')
