---

gluster_server_hostnames: []
gluster_server_brick_path: /export/glusterfs
gluster_server_volume_name: gluster

# http://gluster.readthedocs.org/en/latest/Administrator%20Guide/Setting%20Up%20Volumes/
gluster_server_volume_type: replicate
gluster_server_volume_replicate_count: 1
gluster_server_volume_stripe_count: 1


_gluster_server_volume_replicate_args:
  "replica {{ gluster_server_volume_replicate_count }}"

_gluster_server_volume_stripe_args:
  "stripe {{ gluster_server_volume_stripe_count }}"

_gluster_server_volume_create_args:
  replicate: "{{ _gluster_server_volume_replicate_args }}"
  stripe: "{{ _gluster_server_volume_stripe_args }}"
