---

gluster_server_hostnames: []
gluster_server_brick_path: /export/glusterfs
gluster_server_volume_name: gluster

# http://gluster.readthedocs.org/en/latest/Administrator%20Guide/Setting%20Up%20Volumes/
gluster_server_volume_type: replicated
gluster_server_volume_replicate_count: 1


_gluster_server_volume_replicate_args:
  "replica {{ gluster_server_volume_replicate_count }}"
