---

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zookeeper
    - zookeeper-bin
    - zookeeperd
  tags: zk_install

- name: set instance id
  template:
    src: myid.j2
    dest: /etc/zookeeper/conf/myid
  notify: restart zookeeper
  tags: zk_conf


- name: configure
  template:
    src: zoo.cfg.j2
    dest: /etc/zookeeper/conf/zoo.cfg
  notify: restart zookeeper
  tags: zk_conf
